env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
  project: './tsconfig.json'  # 你的 tsconfig 路径

plugins:
  - '@typescript-eslint'
  - react
  - react-hooks

settings:
  react:
    version: detect  # 自动检测 React 版本

rules:
  # 关闭不必要的规则示例
  react/react-in-jsx-scope: off
  react/jsx-uses-react: off

  # 你可以根据需要自行添加更多规则
