/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/about/': RouteRecordInfo<'/dashboard/about/', '/dashboard/about', Record<never, never>, Record<never, never>>,
    '/dashboard/history/': RouteRecordInfo<'/dashboard/history/', '/dashboard/history', Record<never, never>, Record<never, never>>,
    '/dashboard/upload/': RouteRecordInfo<'/dashboard/upload/', '/dashboard/upload', Record<never, never>, Record<never, never>>,
    '/dashboard/users/': RouteRecordInfo<'/dashboard/users/', '/dashboard/users', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
  }
}
