# 设定字节跳动源
[source.crates-io]
replace-with = 'rsproxy-sparse'
[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"
[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"
[http]
check-revoke = false
[net]
git-fetch-with-cli = true

# 在 Windows MSVC 上，静态链接 C 库，以便编译结果不依赖于 vcruntime DLL
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# 在 linux musl 上，静态链接 C 库，以便编译结果不依赖于其他动态库
[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-self-contained=yes",
]

# 编译优化
[profile.release]
# 删除调试信息
strip = "debuginfo"
# 设置链接时优化
lto = true
