spring:
  application:
    name: SpringBootUndertow
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  threads:
    virtual:
      enabled: true   # 开启虚拟线程（需要Spring Boot 3.4.0）
  profiles:
    active: dev

server:
  port: ${SPRING_HTTP_PORT:8090}   # 默认8090，可通过环境变量SPRING_HTTP_PORT覆盖
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  undertow:
    io-threads: 8                   # IO线程数
    worker-threads: 128             # 阻塞任务线程池
    buffer-size: 1024               # 每个缓冲区的大小
    buffers-per-region: 1024        # 每个区分配的buffer数量
    direct-buffers: true            # 是否使用堆外内存
    max-http-post-size: 0           # HTTP POST请求的最大内容大小（0=不限制）
    no-request-timeout: 1800s       # 空闲超时时间
    session-cookie-config: none     # 会话cookie配置
    accesslog:
      enabled: false                # 访问日志
    enabled-http2: false            # 是否启用HTTP/2
