# 构建Java开发环境
# 使用NeoVim编辑器

# 基础镜像-alpine
FROM maven:3.9.9-eclipse-temurin-21-alpine

# [参数传递]
# 宿主机的用户和组
ARG ARG_USER_ID=1000
ARG ARG_USER_NAME="java21_dev_usr"
ARG ARG_GROUP_ID=1000
ARG ARG_GROUP_NAME="java21_dev_grp"
# Github下载地址
ARG ARG_GITHUB_URL="https://bgithub.xyz"
ARG ARG_CONTAINER_NAME="java21_dev"

# 设定Java用环境变量
# 开启Java21 分代ZGC [-XX:+UseZGC -XX:+ZGenerational]
ENV JAVA_TOOL_OPTIONS="-Duser.language=en -Dfile.encoding=UTF-8 -Dlog4j2.asyncQueueFullPolicy=Discard -Dlog4j2.discardThreshold=ERROR -XX:+UseZGC -XX:+ZGenerational"
# 在nvim中判断用
ENV DOCKER_CONTAINER="true"
ENV DOCKER_CONTAINER_NAME=$ARG_CONTAINER_NAME
ENV DOCKER_CONTAINER_USER=$ARG_USER_NAME
ENV DOCKER_CONTAINER_GROUP=$ARG_GROUP_NAME
# Github下载地址
ENV GITHUB_URL="https://bgithub.xyz"
ENV GITHUB_CONFIG_URL=$ARG_GITHUB_URL
RUN echo "Dev User/Group ID is : ${ARG_USER_ID}/${ARG_GROUP_ID}"
RUN echo "Dev User/Group NAME is : ${ARG_USER_NAME}/${ARG_GROUP_NAME}"
RUN echo "Github URL is : ${GITHUB_URL}"
RUN echo "Github Config URL is : ${GITHUB_CONFIG_URL}"

# 设定alpine镜像仓库为国内源
RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

# 创建开发用户（避免数据卷为权限为root）
RUN addgroup -S -g ${ARG_GROUP_ID} ${DOCKER_CONTAINER_GROUP}
RUN adduser -S -G ${DOCKER_CONTAINER_GROUP} -u ${ARG_USER_ID} --shell /bin/bash ${DOCKER_CONTAINER_USER}

# 安装 所需内容
RUN apk update --quiet
# RUN apk add --no-cache --upgrade bash curl neovim neovim-doc git python3 py3-pip zip wget gzip xsel xclip lazygit ripgrep fd build-base dpkg py3-pynvim
RUN apk add --no-cache --upgrade bash curl neovim neovim-doc git zip wget gzip xsel xclip lazygit ripgrep fd build-base dpkg

# 安装 gosu
# gosu 是经常出现在官方Docker镜像中的一个小工具。它是"su"和"sudo"命令的轻量级替代品，并解决了它们在tty和信号传递中的一些问题
RUN curl -sSL -o /usr/local/bin/gosu "${GITHUB_URL}/tianon/gosu/releases/download/1.17/gosu-$(dpkg --print-architecture | awk -F- '{ print $NF }')"
RUN chmod +x /usr/local/bin/gosu

# 创建工作路径
RUN mkdir /workspace
# 设置工作目录
WORKDIR /workspace

# 修改权限
RUN chown -R $DOCKER_CONTAINER_USER:$DOCKER_CONTAINER_GROUP /workspace

# 切换用户
USER ${DOCKER_CONTAINER_USER}

# 创建Maven设定路径
RUN mkdir -p /home/${DOCKER_CONTAINER_USER}/.m2/repository
# 设定Maven国内源
RUN echo '<?xml version="1.0" encoding="UTF-8"?> \
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" \
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" \
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"> \
    <pluginGroups></pluginGroups> \
    <proxies></proxies> \
    <servers></servers> \
    <mirrors> \
        <!-- 2. 配置阿里云镜像仓库 --> \
        <mirror> \
            <id>alimaven</id> \
            <name>aliyun maven</name> \
            <url>http://maven.aliyun.com/nexus/content/groups/public/</url> \
            <mirrorOf>central</mirrorOf> \
        </mirror> \
    </mirrors> \
</settings> \
' >> /home/${DOCKER_CONTAINER_USER}/.m2/settings.xml

# git设定
RUN git config --global user.name "yourname"
RUN git config --global user.email "your@email.com"
RUN git config --global gui.encoding utf-8
RUN git config --global color.ui true
RUN git config --global core.autoCRLF false
RUN git config --global core.sparseCheckout true
RUN git config --global credential.helper store

# neovim配置一键安装
ENV GITHUB_RAW_URL=https://raw.bgithub.xyz
# ENV GITHUB_RAW_URL=https://raw.bgithub.xyz
RUN curl -fsSL ${GITHUB_RAW_URL}/leoplutos/tecnote/refs/heads/master/Linux/lazy_nvim_setting.sh | bash -

WORKDIR /workspace

# 个人习惯定制化
RUN echo 'PS_GREEN="\[\033[0;32m\]"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'PS_YELLOW="\[\033[0;33m\]"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'PS_BLUE="\[\033[0;34m\]"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'PS_MAGENTA="\[\033[0;35m\]"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'PS_CLEAR="\[\033[0m\]"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'export PS1="${PS_GREEN}[${DOCKER_CONTAINER_NAME}]${PS_MAGENTA}\u@\h${PS_CLEAR}:${PS_YELLOW}\w${PS_CLEAR}\n${PS_BLUE}\$ ${PS_CLEAR}"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'alias ll="ls -hl --full-time --color=auto"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'alias lg="lazygit"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'alias vi="nvim"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc
RUN echo 'alias vim="nvim"' >> /home/${DOCKER_CONTAINER_USER}/.bashrc

# 切换用户
USER root

# 设置默认入口命令
# ENTRYPOINT ["/bin/bash"]
# 使用gosu切换到开发用户
ENTRYPOINT ["sh", "-c", "exec gosu ${DOCKER_CONTAINER_USER} /bin/bash"]
